### PR TITLE
[RSDK-7685] move examples into modular-drivers dir

### PR DESCRIPTION
**Pull request by allisonschiang**

### CODE REVIEW

**Comment by allisonschiang** [comment]
not 100% sure why the previous commits are showing up, maybe because I'm using the same branch as my previous PR to move the files. lmk if this will lead to a problem down the line and I'll create a new branch!

**Comment by mattjperez** [comment]
General it's best to start from a clean branch made from an updated main. This keeps things isolated and easier to review, merge, rebase, etc.

Also, the changes so far only have removals. I don't see the re-organized files anywhere.

**Comment by allisonschiang** [comment]
> General it's best to start from a clean branch made from an updated main. This keeps things isolated and easier to review, merge, rebase, etc.
> 
> Also, the changes so far only have removals. I don't see the re-organized files anywhere.

sounds good, I'll re-pr! the reorganized files were moved into the src folder according to the left bar

image

**Comment by allisonschiang** [comment]
going to create a new branch so commits are cleaner

**Pull request closed without merging**
